### ISSUE TITLE
Unable to find class ElasticSearchStorage

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/FlareControl#19]
I am unable to find this class while compiling DataManagementAPI
CAUSED BY scala.ScalaReflectionException: class ElasticsearchStorage not found.
[error]   scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:123)
[error]   scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:22)
[error]   com.enterprise.datamanagement.Reflection$class.getPrimaryConstructor(Reflection.scala:19)
[error]   com.enterprise.datamanagement.Globals$.getPrimaryConstructor(Globals.scala:10)
[error]   com.enterprise.datamanagement.Globals$.defaultStorage$lzycompute(Globals.scala:48)
[error]   com.enterprise.datamanagement.Globals$.defaultStorage(Globals.scala:48)
[error]   com.enterprise.datamanagement.api.RestApiService$class.$init$(RestApi.scala:30)
[error]   com.enterprise.datamanagement.RestApiTest.<init>(RestApiTest.scala:13)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by ligadata-mjalajel** [comment]
fixed.
